apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: final 
type: Opaque
data:
  # These values are base64 encoded
  DBUSER: cm9vdA==  # root
  DBPWD: Y2xvODM1Z3JvdXA4   # clo835group8 