apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: final 
type: Opaque
data:
  # These values are base64 encoded
  DBUSER: Y2xvODM1Z3JvdXA4  # clo835group8
  DBPWD: Y2xvODM1Z3JvdXA4   # clo835group8 