name: Deploy to ECR

on: 
  push:
    branches: [ current-workspace ]

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest

    steps:

    - name: Check out code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }} 
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        DB_REPOSITORY: clo835-project-db
        APP_REPOSITORY: clo835-project-app
        IMAGE_TAG: ${{ github.sha }}
      run: |
        # mysql image build and push
        docker build -t $ECR_REGISTRY/$DB_REPOSITORY:$IMAGE_TAG -f Dockerfile_mysql . 
        docker push $ECR_REGISTRY/$DB_REPOSITORY:$IMAGE_TAG
        
        # app image build and push 
        docker build -t $ECR_REGISTRY/$APP_REPOSITORY:$IMAGE_TAG -f Dockerfile . 
        docker push $ECR_REGISTRY/$APP_REPOSITORY:$IMAGE_TAG
