#Run the workflow for testing the application 

name: Build and Push to ECR

on:
  push:
    branches: [ current-workspace ]

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: projectclo835group8
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        aws-region: ${{ env.AWS_REGION }}
    
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    
    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        DB_REPOSITORY: clo835-project-db
        APP_REPOSITORY: clo835-project-app
        IMAGE_TAG: ${{ github.sha }}
      run: |
        # mysql image build and push
        docker build -t $ECR_REGISTRY/$DB_REPOSITORY:$IMAGE_TAG -f Dockerfile_mysql . 
        docker push $ECR_REGISTRY/$DB_REPOSITORY:$IMAGE_TAG
        
        # app image build and push 
        docker build -t $ECR_REGISTRY/$APP_REPOSITORY:$IMAGE_TAG -f Dockerfile .
        docker push $ECR_REGISTRY/$APP_REPOSITORY:$IMAGE_TAG
